import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { createTask } from "@/lib/github";

/**
 * AI Family Copilot API
 * Parses natural language into GitHub Issues.
 */
export async function POST(req: Request) {
  const session = await auth();
  if (!session?.accessToken) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const { prompt, repoOwner, repoName } = await req.json();

    // 1. MOCK PARSING (Real implementation would use OpenAI/Grok)
    // "Add a task to buy milk and eggs for Saturday dinner"
    const lowerPrompt = prompt.toLowerCase();
    
    let title = prompt;
    let label = "Maintenance"; // Default

    if (lowerPrompt.includes("buy") || lowerPrompt.includes("grocery") || lowerPrompt.includes("milk")) {
      label = "Groceries";
    } else if (lowerPrompt.includes("bill") || lowerPrompt.includes("pay")) {
      label = "Bills";
    } else if (lowerPrompt.includes("school") || lowerPrompt.includes("homework")) {
      label = "School";
    }

    // Attempt to extract title
    const match = prompt.match(/task to (.*)/i) || prompt.match(/add (.*)/i);
    if (match && match[1]) {
      title = match[1].charAt(0).toUpperCase() + match[1].slice(1);
    }

    // 2. Create the Issue
    const issue = await createTask(
      session.accessToken,
      repoOwner,
      repoName,
      title,
      `Generated by AI Family Copilot\n\nOriginal prompt: "${prompt}"`,
      [label]
    );

    return NextResponse.json({ 
      success: true, 
      issueNumber: issue.number,
      title,
      label
    });

  } catch (error: any) {
    console.error(error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
